# Use vale to lint asciidoc
name: "Check Docs style"

on:
  # push:
  #   branches:
  #   - dev
  workflow_dispatch:
    inputs:
      files:
        description: 'The files to lint'
        default: '.'
        type: string
      vale-flags:
        description: 'The vale ini file to use'
        default: '--config=.vale.ini'
        type: string
      use-default-rules:
        description: 'Use default rules'
        default: true
        type: boolean
      vale-fail-on-error:
        description: 'Report vale errors as a failure'
        default: false
        type: boolean
      reporter:
        description: 'Where action messages are reported'
        type: string
        default: 'github-check'
      separator:
        description: 'Delimiter for input files or folders'
        type: string
        default: ''
      debug:
        description: 'Show debug in log'
        default: false
        type: boolean
  # schedule:
    # - cron:  '00 16 * * *'

jobs:

  docs-lint:
    name: Lint docs
    uses: ./.github/workflows/reusable-docs-lint.yml
    with:
      files: ${{ inputs.files }}
      reporter: ${{ inputs.reporter }}
      vale-fail-on-error: ${{ inputs.vale-fail-on-error }}
      separator: ${{ inputs.separator }}
      vale-flags: ${{ inputs.vale-flags }}
      debug:  ${{ inputs.debug }}
